version: '4.27.2'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: dev
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"